### ISSUE TITLE
Remove public references to Data Manager from services

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGLWebservicesDocumentation#8]
I was a little bit concerned about revealing the names/contact information of SiGL DMS data managers to the public. The project's Contacts are the people that should be utilized in any external usage of the DMS services, not necessarily the poor souls who got enlisted to enter the data into SiGL.  I discussed with Hans, and he agreed that we should remove the public documentation of data managers. This includes removing the HOST resource from the services listing, as well as the references to Data Managers under the Project resource (but maybe also in other places that I didn't catch)?

**Comment by troddick** [comment]
I will remove the data manager projects and data manager role endpoints from the documentation page.

**Comment by troddick** [comment]
done
