### ISSUE TITLE
Contact resource documentation missing?

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGLWebservicesDocumentation#9]
After reviewing the resources, I realized that there is no documentation of the Contacts fields? Should there be? Since we're removing the references to Data Managers, I'd love the services to have clear documentation that they should be using our Contacts instead.

**Comment by troddick** [comment]
I will remove the authentication requirements from accessing Contacts in the services and then update the documentation page with the contact endpoints.

**Comment by troddick** [comment]
done
